name: ctranslate
description: Offline lightweight translation hub for Hausa, Yoruba, and Igbo.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/en_ha.json
    - assets/ha_en.json
    - assets/en_yo.json
    - assets/yo_en.json
    - assets/en_ig.json
    - assets/ig_en.json
