name: ctranslate
description: Offline lightweight translation hub for Hausa, Yoruba, and Igbo.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  

  # Core dependencies
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.2   # (updated for Dart 3.x compatibility)

flutter_launcher_icons:
  android: true            # ✅ Use `true` instead of a string
  ios: true
  image_path: "assets/icon.jpeg"

flutter:
  uses-material-design: true


  assets:
    - assets/en_ha.json
    - assets/ha_en.json
    - assets/en_yo.json
    - assets/yo_en.json
    - assets/en_ig.json
    - assets/ig_en.json
